const SNAKE_SEGMENTS_SIZE = 10;
const SNAKE_SEGMENTS_COLOR = "#FF0000";
const FOOD_COLOR = "#AAAA00";
const SNAKE_MOVEMENT_TIMER_INTERVAL = 50;
const INITIAL_SNAKE_X_INDEX = 1;
const INITIAL_SNAKE_Y_INDEX = 1;
